### PR TITLE
Save exempt app list config in internal storage

### PR DESCRIPTION
**Pull request by TchaikovDriver**
Check external config file existence in ExemptAppPresenter, migrate it if necessary. Also migrate it implicitly in MainActivity only if READ_EXTERNAL_STORAGE permission is granted.

### CODE REVIEW

**Comment by wongsyrone** [comment]
@TchaikovDriver Please sign the CLA.

**Comment by TchaikovDriver** [comment]
> @TchaikovDriver Please sign the CLA.

Done.

**Comment by wongsyrone** [comment]
@oasiscifr Please review.

**Comment by oasiscifr** [comment]
Wow! 🍻

**Pull request merged**
