### PR TITLE
add ipv6 support

### PR DESCRIPTION
**Pull request by wongsyrone**
sync vlan4 and vlan6 ip address, netmask and route with shadowsocks-android
add google ipv6 dns server

shutdown service when onDestroy() is called

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by GreaterFire** [comment]
I prefer IP addresses with 114514 :)

**Comment by Riajyuu** [comment]
@GreaterFire

**Comment by klzgrad** [comment]
I see you fiddling with DNS servers again. I always had this idea about not doing this at all: 1) run a stub resolver that hijacks all DNS queries to 0.0.0.1, 0.0.0.2, etc, and 2) route 0.0.0.1 via socks5h when you translate 0.0.0.1 to the original queried domain name. Then you saved a round trip for the DNS query and the igniter client doesn't need to worry about DNS at all.

**Comment by GreaterFire** [comment]
@klzgrad I've considered and implemented fake DNS IP pool before, and abandoned the idea due to complexity and inelegance involved.

**Pull request merged**
