### PR TITLE
Server list Subscription feature

### PR DESCRIPTION
**Pull request by TchaikovDriver**
- Fix the bug that debug apk and release apk cannot be installed in the same phone because of authorities clashing.
- Add server list subscription feature. Only supports the subscription in format 'TrojanURL1#remark\nTrojanURL2#remark\n...' .

### CODE REVIEW

**Comment by oasiscifr** [comment]
@TchaikovDriver Hi. I think it's more flexable to use json and add at least a key for server list, like 

{"server": [trojan_url1, trojan_url2]}

**Comment by oasiscifr** [comment]
@TchaikovDriver It allows future colaboraters to add independent options.

**Comment by TchaikovDriver** [comment]
> @TchaikovDriver Hi. I think it's more flexable to use json and add at least a key for server list, like 
> 
> {"server": [trojan_url1, trojan_url2]}

Yes, of course, this is more flexible than the format I parse. I prefer the format you suggest too. But the reason that I parse the subscription in this way is that my service provider encode server list in this way.

**Comment by wongsyrone** [comment]
The subscription doesn't have any spec yet.

**Comment by TchaikovDriver** [comment]
> The subscription doesn't have any spec yet.

Alright, I shall keep it as a private release currently.

**Comment by oasiscifr** [comment]
@TchaikovDriver I didn't mean to block this PR because of the format. That's just my advice.

**Comment by wongsyrone** [comment]
@GreaterFire  Any opinion on this feature?

**Comment by GreaterFire** [comment]
@wongsyrone I think splitting Trojan URLs with line breaks makes sense. It might eventually make itself into the standard if users really like it. @oasis What is your reasoning behind putting URLs in a JSON array?

**Comment by TchaikovDriver** [comment]
> @TchaikovDriver I didn't mean to block this PR because of the format. That's just my advice.

I am just concerning about that this format is not so general. Implementing subscription feature in this way might lead to lots of issues complaining the failure of server list updating. As @wongsyrone said, there is no spec about subscription by now. Maybe we can wait until the spec comes out.

**Comment by TchaikovDriver** [comment]
> @wongsyrone I think splitting Trojan URLs with line breaks makes sense. It might eventually make itself into the standard if users really like it. @oasis What is your reasoning behind putting URLs in a JSON array?

Let me introduce the format of subscription in the codes.
Firstly, the whole string is encoded in BASE64. After decoding, all the servers are divided by line breaks(`\r\n`, it is probably generated in Windows). In each line, the profile is in format `TrojanURL#ServerRemark`. Split the line by `#` and you will get a Trojan URL and its remark name.

**Pull request merged**
