### PR TITLE
Support json files

### PR DESCRIPTION
**Pull request by imwcc**
Signed-off-by: imwcc <imwcc@qq.com>

### CODE REVIEW

**Comment by imwcc** [comment]
请支持 json 文件格式.
如果只针对 text,对使用者很不方便.

**Comment by wongsyrone** [comment]
@TchaikovDriver Please review.

**Comment by TchaikovDriver** [comment]
> @TchaikovDriver Please review.

LGTM.

**Comment by wongsyrone** [comment]
Please sign the CLA

**Comment by imwcc** [comment]
done

**Comment by wongsyrone** [comment]
> Wang, Arvin seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

**Comment by imwcc** [comment]
The conflict is due to git-config and signature conflicts Signed-off-by: Wang, Arvin imwcc@qq.com.
I need to add an email address to my account at next week.

**Comment by imwcc** [comment]
Hi @wongsyrone 
I force update PR.
Only update the commit message.
Please review again.

**Pull request merged**
