### PR TITLE
Migrate to ML Kit for scanning QR code

### PR DESCRIPTION
**Pull request by TchaikovDriver**
- Import CameraX for image analysis.
- Migrate from bingoogolapple/BGAQRCode-Android to ML Kit for QR code scanning.

### CODE REVIEW

**Comment by wongsyrone** [comment]
Thanks for the PR. I don't understand why the CameraX library is Kotlin-only. Do you have any references for it?

Some refs:

https://developer.android.com/jetpack/androidx/releases/camera#dependencies
https://developer.android.com/training/camerax/configuration#java
https://developers.google.com/ml-kit/vision/barcode-scanning/android#java

**Comment by TchaikovDriver** [comment]
> Thanks for the PR. I don't understand why the CameraX library is Kotlin-only. Do you have any references for it?
> 
> Some refs:
> 
> https://developer.android.com/jetpack/androidx/releases/camera#dependencies
> https://developer.android.com/training/camerax/configuration#java
> https://developers.google.com/ml-kit/vision/barcode-scanning/android#java

Sorry for confusing you, I saw the start [tutorial](https://codelabs.developers.google.com/codelabs/camerax-getting-started/#1) of CameraX which mentions adding `apply plugin: 'kotlin-android-extensions'` at the top of the file `build.gradle`. Then I considered that CameraX requires kotlin support.
In conclusion, CameraX is not Kotlin-only, since Kotlin is compatible to Java.

**Comment by wongsyrone** [comment]
@TchaikovDriver Do you have any plan to rewrite it in Java?

**Comment by TchaikovDriver** [comment]
> @TchaikovDriver Do you have any plan to rewrite it in Java?

That's easy, but just a bit later, will make a commit in these days.

**Comment by wongsyrone** [comment]
LGTM. Thanks for the PR.

**Pull request merged**
