### PR TITLE
Change the layout of MainActivity.

### PR DESCRIPTION
**Pull request by Alexinst**
- Use a ScrollView as the outter layout, and a ConstraintLayout as the inner layout. Remove the LinearLayout.
- Enlarge the font size.
- Enlarge the button size.

It might be better looking.

### CODE REVIEW

**Comment by oasiscifr** [comment]
@Alexinst ?

**Comment by Alexinst** [comment]
@oasiscifr I change the UI of home page. The origin layout seems not that good.

**Comment by oasiscifr** [comment]
@Alexinst I commented a "only a question mark" just because at that time, you didn't provide any description about your pr. I think it's good to reply "barely nothing" with "only a ?"🙈

**Comment by Alexinst** [comment]
Sorry, I have no enough experience of commiting a PR. I have added the description of the changes. Hope it's helpful.

**Comment by oasiscifr** [comment]
@Alexinst  I believe that your PR will be reviewed next month after a major change, https://github.com/trojan-gfw/igniter/pull/29. The BDFL of igniter is busy now :P .

**Comment by Alexinst** [comment]
@oasiscifr OK. -_-

**Comment by GreaterFire** [comment]
@Alexinst Thanks for your contribution! Since another PR has been merged, there has been modifications to the UI, resulting in a merge conflict. Can you resolve it?

**Pull request closed without merging**
