### PR TITLE
Exempt app branch

### PR DESCRIPTION
**Pull request by TchaikovDriver**
Implement application-oriented bypass feature.

### CODE REVIEW

**Comment by wongsyrone** [comment]
Did you save the app list to the config file?

**Comment by wongsyrone** [comment]
I skimmed the commit without testing, looks good to me. I'm currently debugging the crash bug.

**Comment by TchaikovDriver** [comment]
> Did you save the app list to the config file?

No, I save the exempted app package names in SharedPreferences, which is easier to read and write. I think the size of exempted app list won't be large, so it would be better to be stored in SharedPreferences rather than in file.

**Comment by wongsyrone** [comment]
Can you get disabled application metadata?

**Pull request merged**
